### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by Coirt** [8Mode/8Mode-VCV_Modules#4]
There is still a lot of interest for this module being in VCV. Do you have plans to migrate to Rack v1?

**Comment by 8Mode** [comment]
> There is still a lot of interest for this module being in VCV. Do you have plans to migrate to Rack v1?

Yes. I started the migration last night and should have it done this weekend. 
Thanks. Glad there is interest in this module!

**Comment by Coirt** [comment]
Great!

**Comment by pgatt** [comment]
Looking forward to being able to use this module again!

Thanks for the work updating it.

**Comment by pgatt** [comment]
Any news as to the progress on this: there is interest in the new Vult Atari module which has again raised the interest in Commodore style sounds.

**Comment by netboy3** [comment]
Just completed migrating the plugin to Rack V1. I've also posted a pull request for the original developer to merge my update into their code. I have also built the plugins and have them here for users to test out the new builds:

Linux: [8Mode-1.0.0-lin.zip](https://github.com/8Mode/8Mode-VCV_Modules/files/3753450/8Mode-1.0.0-lin.zip)
Mac: [8Mode-1.0.0-mac.zip](https://github.com/8Mode/8Mode-VCV_Modules/files/3753451/8Mode-1.0.0-mac.zip)
Windows: [8Mode-1.0.0-win.zip](https://github.com/8Mode/8Mode-VCV_Modules/files/3753452/8Mode-1.0.0-win.zip)

Please let me know if you find any issues. I hope you enjoy the fun of the SoftSN Machine again. It's a fun plugin that really strikes a cord with discrete electronics hobbyists. 8Mode - Thanks for writing this plugin.

**Comment by The-Great-Assyr** [comment]
> Just completed migrating the plugin to Rack V1. I've also posted a pull request for the original developer to merge my update into their code. I have also built the plugins and have them here for users to test out the new builds

Thank you for this! <3 I just downloaded and installed and so far (13th Nov 2019) it works perfectly. So happy to have this awesome plugin back in VCV! :-D

**Comment by msdlogic** [comment]
> Just completed migrating the plugin to Rack V1. I've also posted a pull request for the original developer to merge my update into their code. I have also built the plugins and have them here for users to test out the new builds:
> 
> Linux: [8Mode-1.0.0-lin.zip](https://github.com/8Mode/8Mode-VCV_Modules/files/3753450/8Mode-1.0.0-lin.zip)
> Mac: [8Mode-1.0.0-mac.zip](https://github.com/8Mode/8Mode-VCV_Modules/files/3753451/8Mode-1.0.0-mac.zip)
> Windows: [8Mode-1.0.0-win.zip](https://github.com/8Mode/8Mode-VCV_Modules/files/3753452/8Mode-1.0.0-win.zip)
> 
> Please let me know if you find any issues. I hope you enjoy the fun of the SoftSN Machine again. It's a fun plugin that really strikes a cord with discrete electronics hobbyists. 8Mode - Thanks for writing this plugin.

Oh wow. I've been away all this time so I haven't gotten this. I'll see about the pulls in and going. Thank you thank you.

**Comment by msdlogic** [comment]
Module is now published. Thanks everyone
